spring:
  application:
    name: bolg_system
  profiles:
    active: jdbc,redis
  datasource:
    url: jdbc:mysql://192.168.159.129:3306/bolg_system?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    闲杂人等连接这个
#    url: jdbc:mysql://192.168.218.232:3306/bolg_system?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: i18n/logo
  mail:
    host: smtp.qq.com
    port: 587
    username: 3606195422@qq.com
    password: uoqwuuyvjdaycjcj
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
COOKIE:
  VALIDITY: 1800

